### ISSUE TITLE
运行python3 daemon.py start出错

### ISSUE THREAD

**Issue by de-conf** [Z4HD/coolq-telegram-bot-docker#2]
[root][ERROR] (daemon.py:21): Unhandled exception: Traceback (most recent call last):
  File "daemon.py", line 54, in <module>
    from bot_constant import *
  File "/home/user/coolq-telegram-bot/bot_constant.py", line 18, in <module>
    settingsJSON = json.loads(f1.read())
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 14 column 19 (char 379)

**Comment by seiuneko** [comment]
@chenjiageng 看样子是 json 写错了？

（而且你也应该在 [jqqqqqqqqqq/coolq-telegram-bot](https://github.com/jqqqqqqqqqq/coolq-telegram-bot) 提 issue

**Comment by de-conf** [comment]
@xyf1219 好的👌，谢谢！
